services:
  app:
    container_name: down_detector_v1.0.0
    image: down_detector:1.0.0
    build:
      context: .
    env_file:
      - ".env.docker"
    ports:
      - 8888:8888
    networks:
      - "down_detector_net"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: "poetry run python ./src/gunicorn/run.py"
    volumes:
      - ./logs:/app/logs

    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /app/src

  redis:
    container_name: "down_detector_redis"
    image: "redis"
    ports:
      - "7379:6379"
    networks:
      - "down_detector_net"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    container_name: down_detector_postgres_db
    image: "postgres:17"
    ports:
      - 6432:5432
    volumes:
      - pg_db_data:/var/lib/postgresql/data
    networks:
      - "down_detector_net"
    env_file:
      - ".env.postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      

volumes:
  pg_db_data:

networks:
  down_detector_net:
    driver: bridge
